// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package custom

import (
	"time"

	"gorm.io/gorm"
)

const TableNameXEnterprise = "x_enterprise"

// XEnterprise 企业表
type XEnterprise struct {
	ID          uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	PID         uint32         `gorm:"column:p_id;type:int unsigned;not null;index:p_id,priority:1;comment:企业所属园区ID" json:"p_id"`   // 企业所属园区ID
	Type        int32          `gorm:"column:type;type:tinyint;not null;index:p_id,priority:2;comment:企业类型（1：企业；2：学院）" json:"type"` // 企业类型（1：企业；2：学院）
	FullName    string         `gorm:"column:full_name;type:varchar(50);not null;comment:企业全称" json:"full_name"`                    // 企业全称
	ShortName   string         `gorm:"column:short_name;type:varchar(50);not null;comment:企业简称" json:"short_name"`                  // 企业简称
	Description string         `gorm:"column:description;type:longtext;not null;comment:企业简介" json:"description"`                   // 企业简介
	Icon        string         `gorm:"column:icon;type:varchar(255);not null;comment:企业图标" json:"icon"`                             // 企业图标
	Image       string         `gorm:"column:image;type:longtext;not null;comment:企业图片" json:"image"`                               // 企业图片
	Contact     string         `gorm:"column:contact;type:longtext;not null;comment:联系方式" json:"contact"`                           // 联系方式
	Website     string         `gorm:"column:website;type:longtext;not null;comment:企业官网" json:"website"`                           // 企业官网
	Label       string         `gorm:"column:label;type:longtext;not null;comment:标签" json:"label"`                                 // 标签
	LeaseTime   time.Time      `gorm:"column:lease_time;type:date;not null;comment:入驻时间" json:"lease_time"`                         // 入驻时间
	Top         int32          `gorm:"column:top;type:tinyint;not null;comment:置顶状态（1：置顶；0：不置顶）" json:"top"`                        // 置顶状态（1：置顶；0：不置顶）
	Weight      int32          `gorm:"column:weight;type:int;not null;comment:权重" json:"weight"`                                    // 权重
	Status      int32          `gorm:"column:status;type:tinyint;not null;default:1;comment:账号状态（1：启用；-1：禁用）" json:"status"`        // 账号状态（1：启用；-1：禁用）
	CreatedBy   uint32         `gorm:"column:created_by;type:int unsigned;not null;comment:创建人ID" json:"created_by"`                // 创建人ID
	UpdatedBy   uint32         `gorm:"column:updated_by;type:int unsigned;not null;comment:修改人ID" json:"updated_by"`                // 修改人ID
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp;not null;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp;not null;comment:修改时间" json:"updated_at"`                    // 修改时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                             // 删除时间
}

// TableName XEnterprise's table name
func (*XEnterprise) TableName() string {
	return TableNameXEnterprise
}
