// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package custom

import (
	"time"

	"gorm.io/gorm"
)

const TableNameXUserIdentityVerification = "x_user_identity_verification"

// XUserIdentityVerification 用户实名认证表
type XUserIdentityVerification struct {
	ID        uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                   // 主键ID
	UID       uint32         `gorm:"column:u_id;type:int unsigned;not null;uniqueIndex:uk_u_id,priority:1;comment:用户ID" json:"u_id"`     // 用户ID
	Channel   string         `gorm:"column:channel;type:varchar(20);not null;comment:认证渠道" json:"channel"`                               // 认证渠道
	Name      string         `gorm:"column:name;type:varchar(10);not null;comment:姓名" json:"name"`                                       // 姓名
	IDCard    string         `gorm:"column:id_card;type:varchar(100);not null;comment:身份证号码" json:"id_card"`                             // 身份证号码
	Hash      string         `gorm:"column:hash;type:char(64);not null;index:idx_hash,priority:1;comment:身份证号码Hash" json:"hash"`         // 身份证号码Hash
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"updated_at"` // 修改时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;index:idx_deleted_at,priority:1;comment:删除时间" json:"deleted_at"`    // 删除时间
}

// TableName XUserIdentityVerification's table name
func (*XUserIdentityVerification) TableName() string {
	return TableNameXUserIdentityVerification
}
