// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package custom

import (
	"time"

	"gorm.io/gorm"
)

const TableNameXUserEnterprise = "x_user_enterprise"

// XUserEnterprise 用户企业关联表
type XUserEnterprise struct {
	ID        uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID       uint32         `gorm:"column:u_id;type:int unsigned;not null;index:u_id,priority:1;comment:用户ID" json:"u_id"` // 用户ID
	EID       uint32         `gorm:"column:e_id;type:int unsigned;not null;index:e_id,priority:1;comment:企业ID" json:"e_id"` // 企业ID
	PID       uint32         `gorm:"column:p_id;type:int unsigned;not null;index:p_id,priority:1;comment:园区ID" json:"p_id"` // 园区ID
	Type      int32          `gorm:"column:type;type:tinyint;not null;comment:入职企业类型（1：企业；2：学院）" json:"type"`               // 入职企业类型（1：企业；2：学院）
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;not null;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp;not null;comment:修改时间" json:"updated_at"`              // 修改时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                       // 删除时间
}

// TableName XUserEnterprise's table name
func (*XUserEnterprise) TableName() string {
	return TableNameXUserEnterprise
}
