// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameXUser = "x_user"

// XUser 用户表
type XUser struct {
	ID                 uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name               string         `gorm:"column:name;type:varchar(11);not null;comment:姓名" json:"name"`                                                      // 姓名
	Avatar             string         `gorm:"column:avatar;type:varchar(255);not null;comment:头像" json:"avatar"`                                                 // 头像
	BlockStatus        int32          `gorm:"column:block_status;type:tinyint;not null;comment:拉黑状态（1：未拉黑；2：已拉黑）" json:"block_status"`                           // 拉黑状态（1：未拉黑；2：已拉黑）
	AccountStatus      int32          `gorm:"column:account_status;type:tinyint;not null;comment:账号状态（1：正常；2：禁用）" json:"account_status"`                         // 账号状态（1：正常；2：禁用）
	Account            string         `gorm:"column:account;type:varchar(50);not null;uniqueIndex:account,priority:1;comment:账号" json:"account"`                 // 账号
	PhoneNumber        string         `gorm:"column:phone_number;type:varchar(50);not null;uniqueIndex:phone_number,priority:1;comment:手机号" json:"phone_number"` // 手机号
	Gender             int32          `gorm:"column:gender;type:tinyint;not null;comment:性别（0：保密；1：男；2：女）" json:"gender"`                                        // 性别（0：保密；1：男；2：女）
	VerificationStatus int32          `gorm:"column:verification_status;type:tinyint;not null;comment:实名认证状态（1：已认证；0：未认证）" json:"verification_status"`           // 实名认证状态（1：已认证；0：未认证）
	GraduatedSchool    string         `gorm:"column:graduated_school;type:varchar(50);not null;comment:毕业院校" json:"graduated_school"`                            // 毕业院校
	Profession         string         `gorm:"column:profession;type:varchar(50);not null;comment:职业" json:"profession"`                                          // 职业
	Residence          string         `gorm:"column:residence;type:varchar(50);not null;comment:居住地" json:"residence"`                                           // 居住地
	Contact            string         `gorm:"column:contact;type:varchar(50);not null;comment:联系方式" json:"contact"`                                              // 联系方式
	WorkYears          float64        `gorm:"column:work_years;type:double(10,2);not null;comment:工作年限" json:"work_years"`                                       // 工作年限
	Introduction       string         `gorm:"column:introduction;type:varchar(255);not null;comment:个人简介" json:"introduction"`                                   // 个人简介
	Skills             string         `gorm:"column:skills;type:text;not null;comment:核心技能，多个使用分号分割" json:"skills"`                                              // 核心技能，多个使用分号分割
	DeactivateStatus   int32          `gorm:"column:deactivate_status;type:tinyint;not null;comment:注销状态（0：未注销；1：注销中；2：已注销）" json:"deactivate_status"`           // 注销状态（0：未注销；1：注销中；2：已注销）
	DeactivateAt       *time.Time     `gorm:"column:deactivate_at;type:timestamp;comment:注销时间" json:"deactivate_at"`                                             // 注销时间
	CreatedAt          time.Time      `gorm:"column:created_at;type:timestamp;not null;comment:创建时间" json:"created_at"`                                          // 创建时间
	UpdatedAt          time.Time      `gorm:"column:updated_at;type:timestamp;not null;comment:修改时间" json:"updated_at"`                                          // 修改时间
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                                                   // 删除时间
}

// TableName XUser's table name
func (*XUser) TableName() string {
	return TableNameXUser
}
