// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"portal/internal/app"
	"portal/internal/config"
	enterprise2 "portal/internal/handler/enterprise"
	health2 "portal/internal/handler/health"
	user2 "portal/internal/handler/user"
	"portal/internal/infra"
	"portal/internal/repository"
	"portal/internal/service/enterprise"
	"portal/internal/service/health"
	"portal/internal/service/user"
)

// Injectors from wire.go:

func wireDIContainer() (*app.DIContainer, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	redisConfig := config.LoadRedisConfig(configConfig)
	universalClient, err := infra.InitRedis(redisConfig)
	if err != nil {
		return nil, err
	}
	cache := repository.Cache{
		RedisDB: universalClient,
	}
	mysqlConfig := config.LoadMysqlConfig(configConfig)
	db, err := infra.InitMysql(configConfig, mysqlConfig)
	if err != nil {
		return nil, err
	}
	userRepo := repository.UserRepo{
		DB: db,
	}
	enterpriseRepo := repository.EnterpriseRepo{
		DB: db,
	}
	userEnterpriseRepo := repository.UserEnterpriseRepo{
		DB: db,
	}
	service := enterprise.Service{
		Cache:              cache,
		Config:             configConfig,
		UserRepo:           userRepo,
		EnterpriseRepo:     enterpriseRepo,
		UserEnterpriseRepo: userEnterpriseRepo,
	}
	handler := &enterprise2.Handler{
		EnterpriseService: service,
	}
	repositoryCache := &repository.Cache{
		RedisDB: universalClient,
	}
	repositoryUserRepo := &repository.UserRepo{
		DB: db,
	}
	repositoryEnterpriseRepo := &repository.EnterpriseRepo{
		DB: db,
	}
	repositoryUserEnterpriseRepo := &repository.UserEnterpriseRepo{
		DB: db,
	}
	userService := &user.Service{
		Cache:              repositoryCache,
		Config:             configConfig,
		UserRepo:           repositoryUserRepo,
		EnterpriseRepo:     repositoryEnterpriseRepo,
		UserEnterpriseRepo: repositoryUserEnterpriseRepo,
	}
	userHandler := &user2.Handler{
		UserService: userService,
	}
	healthService := health.NewService(db, universalClient)
	healthHandler := health2.NewHandler(healthService)
	enterpriseService := &enterprise.Service{
		Cache:              cache,
		Config:             configConfig,
		UserRepo:           userRepo,
		EnterpriseRepo:     enterpriseRepo,
		UserEnterpriseRepo: userEnterpriseRepo,
	}
	limiter := infra.InitRedisLimiter(universalClient)
	diContainer := &app.DIContainer{
		Config:            configConfig,
		EnterpriseHandler: handler,
		UserHandler:       userHandler,
		HealthHandler:     healthHandler,
		EnterpriseService: enterpriseService,
		UserService:       userService,
		HealthService:     healthService,
		UserRepo:          repositoryUserRepo,
		EnterpriseRepo:    repositoryEnterpriseRepo,
		Cache:             repositoryCache,
		RateLimiter:       limiter,
		MysqlDB:           db,
	}
	return diContainer, nil
}

// wire.go:

// 配置项注入
var configSet = wire.NewSet(config.LoadConfig, config.LoadMysqlConfig, config.LoadRedisConfig)

// 存储连接和相关工具注入
var dbSet = wire.NewSet(infra.InitMysql, infra.InitRedis, infra.InitRedisLimiter)
