// Code generated by cams. DO NOT EDIT.

package ginx

import (
	"errors"
	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
	"github.com/go-playground/validator/v10"
)

func ShouldBindUrl(ctx *gin.Context, obj any) error {
	var validationErrors validator.ValidationErrors

	// 先解析 Path
	err := ctx.ShouldBindUri(obj)
	if errors.As(err, &validationErrors) && len(validationErrors) > 0 {
		return Translate(ctx, validationErrors[0])
	}

	// 再解析 Query
	err = ctx.ShouldBindQuery(obj)
	if errors.As(err, &validationErrors) && len(validationErrors) > 0 {
		return Translate(ctx, validationErrors[0])
	}
	return err
}

// ShouldBind 表单解析，返回校验的第一个错误
func ShouldBind(ctx *gin.Context, obj any) error {
	err := ctx.ShouldBind(obj)
	var validationErrors validator.ValidationErrors
	if errors.As(err, &validationErrors) && len(validationErrors) > 0 {
		return Translate(ctx, validationErrors[0])
	}
	return err
}

// ShouldBindUri 表单解析，返回校验的第一个错误
func ShouldBindUri(ctx *gin.Context, obj any) error {
	err := ctx.ShouldBindUri(obj)
	var validationErrors validator.ValidationErrors
	if errors.As(err, &validationErrors) && len(validationErrors) > 0 {
		return Translate(ctx, validationErrors[0])
	}
	return err
}

// ShouldBindWith 表单解析，返回校验的第一个错误
func ShouldBindWith(ctx *gin.Context, obj any, b binding.Binding) error {
	err := ctx.ShouldBindWith(obj, b)
	var validationErrors validator.ValidationErrors
	if errors.As(err, &validationErrors) && len(validationErrors) > 0 {
		return Translate(ctx, validationErrors[0])
	}
	return err
}
