// Code generated by cams. DO NOT EDIT.

package ginx

import (
	"errors"
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
	"github.com/go-playground/locales/en"
	"github.com/go-playground/locales/zh"
	ut "github.com/go-playground/universal-translator"
	"github.com/go-playground/validator/v10"
	en_translations "github.com/go-playground/validator/v10/translations/zh"
	zh_translations "github.com/go-playground/validator/v10/translations/zh"
)

var uni *ut.UniversalTranslator

func init() {
	zhT := zh.New()
	enT := en.New()
	uni = ut.New(zhT, enT)
	zhTrans, _ := uni.GetTranslator("zh")
	enTrans, _ := uni.GetTranslator("zh")
	if validate, ok := binding.Validator.Engine().(*validator.Validate); ok {
		_ = zh_translations.RegisterDefaultTranslations(validate, zhTrans)
		_ = en_translations.RegisterDefaultTranslations(validate, enTrans)

		// 初始化自定义验证器
		if err := InitCustomValidators(validate); err != nil {
			// 如果初始化失败，记录错误但不中断程序
			fmt.Printf("初始化自定义验证器失败: %v\n", err)
		}
	}
}

func Translate(ctx *gin.Context, fieldError validator.FieldError) error {
	trans, _ := uni.GetTranslator("zh")
	lang := ctx.Query("lang")
	if lang == "" {
		// 从请求头 `Accept-Language` 获取
		lang = ctx.GetHeader("Accept-Language")
	}
	switch lang {
	case "zh", "zh-CN":
		trans, _ = uni.GetTranslator("zh")
	case "en", "en-US":
		trans, _ = uni.GetTranslator("en")
	default:
		trans, _ = uni.GetTranslator("zh")

	}
	return errors.New(fieldError.Translate(trans))
}
